"""Build sleeve_alpha_dev.ipynb (local POC twin of sleeve_alpha.ipynb).

Re-runnable scaffolder. Output is the dev notebook with Section 0/1
identifier set matching the Cron2 contract (prices_panel, iv_panel,
iv90_panel, iv90mny, skew_panel, vix, vvix, rf_rate).
"""
import json
import pathlib

NB = pathlib.Path("sleeve_alpha_dev.ipynb")


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def code(*lines):
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": list(lines),
    }


cells = [
    md(
        "# Options Quant — Sleeve Allocation Framework (α Engine, **local POC**)\n",
        "\n",
        "Local twin of `sleeve_alpha.ipynb`. All-official free data: CBOE (SPX/VIX/VIX3M/SKEW/VXN) ",
        "+ FRED (NASDAQ100/DGS3MO). Produces the same identifier set so Section 2+ math copies ",
        "back to the Cron2 notebook verbatim.\n",
        "\n",
        "Universe: SPX (S&P 500 index) and NDX (NASDAQ-100 index). Full signal stack on both — ",
        "iv30_90mny and NDX iv90_atm are synthesized from VIX/VXN/SKEW (POC; absolute level ",
        "uncalibrated, monotonic enough for percentile-rank signals).\n",
    ),
    md("## Section 0 — Setup & Config\n"),
    code(
        "import pathlib\n",
        "import warnings\n",
        "import datetime as dt\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import pandas_market_calendars as mcal\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from local_data import con  # FreeCon — drop-in for Cron2 emds_client.con\n",
    ),
    code(
        'UNDERLYINGS = {\n',
        '    "SPX": "SPX Index",\n',
        '    "NDX": "NDX Index",\n',
        '}\n',
        'REQUIRED_UNDERLYINGS = ("SPX", "NDX")\n',
        '\n',
        'IV_FIELDS = {\n',
        '    "iv30_atm":   "30DAY_IMPVOL_100.0%MNY_DF",\n',
        '    "iv30_90mny": "30DAY_IMPVOL_90.0%MNY_DF",\n',
        '    "iv90_atm":   "90DAY_IMPVOL_100.0%MNY_DF",\n',
        '}\n',
        'PRICE_FIELD = "PX_LAST"\n',
        '\n',
        'CROSS_ASSET = {\n',
        '    "vix":     ("VIX Index",     "PX_LAST"),\n',
        '    "rf_rate": ("USGG3M Index",  "PX_LAST"),\n',
        '}\n',
        '\n',
        'START_DATE = "2010-01-01"\n',
        'END_DATE   = dt.date.today().isoformat()\n',
    ),
    code(
        'def nyse_index(start, end):\n',
        '    sched = mcal.get_calendar("NYSE").schedule(start_date=start, end_date=end)\n',
        '    return pd.DatetimeIndex(sched.index).normalize()\n',
        '\n',
        'NYSE_INDEX = nyse_index(START_DATE, END_DATE)\n',
        'print(f"NYSE_INDEX: n={len(NYSE_INDEX)}, {NYSE_INDEX.min().date()} → {NYSE_INDEX.max().date()}")\n',
    ),
    md("## Section 1 — Data Layer\n", "\n", "### 1.1 Raw pulls (per-underlying, per-field)\n"),
    code(
        'raw_pulls = {u: {} for u in UNDERLYINGS}\n',
        'for u, ticker in UNDERLYINGS.items():\n',
        '    raw_pulls[u]["price"] = con.bdh(ticker, PRICE_FIELD, START_DATE, END_DATE)\n',
        '    for fkey, fname in IV_FIELDS.items():\n',
        '        raw_pulls[u][fkey] = con.bdh(ticker, fname, START_DATE, END_DATE)\n',
        '\n',
        'pull_log = []\n',
        'for u in UNDERLYINGS:\n',
        '    for fkey, df in raw_pulls[u].items():\n',
        '        pull_log.append({\n',
        '            "underlying": u, "field": fkey,\n',
        '            "n": len(df),\n',
        '            "status": "landed" if len(df) else "deferred",\n',
        '        })\n',
        'pd.DataFrame(pull_log).pivot(index="underlying", columns="field", values="n").fillna(0).astype(int)\n',
    ),
    md("### 1.2 Cross-asset pulls\n"),
    code(
        'raw_cross = {}\n',
        'for name, (ticker, field) in CROSS_ASSET.items():\n',
        '    raw_cross[name] = con.bdh(ticker, field, START_DATE, END_DATE)\n',
        '\n',
        'pd.DataFrame({\n',
        '    "ticker": [CROSS_ASSET[k][0] for k in raw_cross],\n',
        '    "n":      [len(raw_cross[k]) for k in raw_cross],\n',
        '    "status": ["landed" if len(raw_cross[k]) else "deferred" for k in raw_cross],\n',
        '}, index=list(raw_cross))\n',
    ),
    md(
        "### 1.3 Panel assembly\n",
        "\n",
        "Wide panels on `NYSE_INDEX`. Naming: `iv90mny` is the 90%-moneyness 30D IV (skew leg). ",
        "`iv90_panel` is the 90D ATM IV probe. `skew_panel = iv90mny - iv_panel`. ",
        "Truncated to the shortest IV history per D-04.\n",
    ),
    code(
        'def _to_series(df, name):\n',
        '    if df is None or len(df) == 0:\n',
        '        return None\n',
        '    s = df.squeeze()\n',
        '    if isinstance(s, pd.DataFrame):\n',
        '        s = s.iloc[:, 0]\n',
        '    s.index = pd.DatetimeIndex(s.index).normalize()\n',
        '    s.name = name\n',
        '    return s\n',
        '\n',
        'def _build_panel(field_key, underlyings_with_data):\n',
        '    cols = {}\n',
        '    for u in underlyings_with_data:\n',
        '        s = _to_series(raw_pulls[u][field_key], u)\n',
        '        if s is not None:\n',
        '            cols[u] = s.reindex(NYSE_INDEX)\n',
        '    return pd.DataFrame(cols, index=NYSE_INDEX)\n',
        '\n',
        'landed = [\n',
        '    u for u in UNDERLYINGS\n',
        '    if len(raw_pulls[u].get("price", pd.DataFrame())) > 0\n',
        '    and len(raw_pulls[u].get("iv30_atm", pd.DataFrame())) > 0\n',
        '    and len(raw_pulls[u].get("iv30_90mny", pd.DataFrame())) > 0\n',
        ']\n',
        'print(f"Landed underlyings: {landed}")\n',
        '\n',
        'prices_panel_full = _build_panel("price",      list(UNDERLYINGS))\n',
        'iv_panel_full     = _build_panel("iv30_atm",   landed)\n',
        'iv90mny_full      = _build_panel("iv30_90mny", landed)\n',
        'iv90_panel_full   = _build_panel(\n',
        '    "iv90_atm",\n',
        '    [u for u in landed if len(raw_pulls[u].get("iv90_atm", pd.DataFrame())) > 0],\n',
        ')\n',
        '\n',
        'iv_first_dates = []\n',
        'for u in landed:\n',
        '    s = iv_panel_full[u].dropna()\n',
        '    if len(s):\n',
        '        iv_first_dates.append(s.index.min())\n',
        'truncate_start = max(iv_first_dates) if iv_first_dates else NYSE_INDEX.min()\n',
        'print(f"Truncating to start={truncate_start.date()} (shortest IV history)")\n',
        '\n',
        'mask = NYSE_INDEX >= truncate_start\n',
        'prices_panel = prices_panel_full.loc[mask].copy()\n',
        'iv_panel     = iv_panel_full.loc[mask].copy()\n',
        'iv90mny      = iv90mny_full.loc[mask].copy()\n',
        'iv90_panel   = iv90_panel_full.loc[mask].copy()\n',
        '\n',
        'common_skew_cols = [c for c in iv_panel.columns if c in iv90mny.columns]\n',
        'skew_panel = iv90mny[common_skew_cols] - iv_panel[common_skew_cols]\n',
        '\n',
        'pd.DataFrame({\n',
        '    "prices_panel": prices_panel.notna().sum(),\n',
        '    "iv_panel":     iv_panel.reindex(columns=prices_panel.columns).notna().sum(),\n',
        '    "iv90_panel":   iv90_panel.reindex(columns=prices_panel.columns).notna().sum(),\n',
        '    "skew_panel":   skew_panel.reindex(columns=prices_panel.columns).notna().sum(),\n',
        '}).T\n',
    ),
    md("### 1.4 Cross-asset Series\n"),
    code(
        'def _to_named_series(name):\n',
        '    df = raw_cross.get(name, pd.DataFrame())\n',
        '    if df is None or len(df) == 0:\n',
        '        s = pd.Series(index=NYSE_INDEX, dtype="float64", name=name)\n',
        '    else:\n',
        '        s = df.squeeze()\n',
        '        if isinstance(s, pd.DataFrame):\n',
        '            s = s.iloc[:, 0]\n',
        '        s.index = pd.DatetimeIndex(s.index).normalize()\n',
        '        s.name = name\n',
        '        s = s.reindex(NYSE_INDEX)\n',
        '    return s.loc[NYSE_INDEX >= truncate_start]\n',
        '\n',
        'vix     = _to_named_series("vix")\n',
        'rf_rate = _to_named_series("rf_rate")\n',
        '\n',
        'for s in (vix, rf_rate):\n',
        '    assert isinstance(s, pd.Series), f"{s.name} must be a Series, got {type(s)}"\n',
        '    assert s.index.equals(prices_panel.index), f"{s.name} index mismatch"\n',
        '\n',
        'pd.DataFrame({\n',
        '    "n_obs":   [s.notna().sum() for s in (vix, rf_rate)],\n',
        '    "first":   [s.dropna().index.min() if s.notna().any() else None for s in (vix, rf_rate)],\n',
        '    "last":    [s.dropna().index.max() if s.notna().any() else None for s in (vix, rf_rate)],\n',
        '    "latest":  [s.dropna().iloc[-1] if s.notna().any() else None for s in (vix, rf_rate)],\n',
        '}, index=["vix","rf_rate"])\n',
    ),
    md("### 1.5 Quick visual sanity check\n"),
    code(
        'fig, axes = plt.subplots(3, 1, figsize=(11, 8), sharex=True)\n',
        'prices_panel[[c for c in ("SPX","NDX") if c in prices_panel.columns]].plot(ax=axes[0], title="Price level (index)")\n',
        'iv_panel[[c for c in ("SPX","NDX") if c in iv_panel.columns]].plot(ax=axes[1], title="30D ATM IV")\n',
        'if "SPX" in skew_panel.columns:\n',
        '    skew_panel[["SPX"]].plot(ax=axes[2], title="SPX 30D skew (90mny − ATM, synthetic)")\n',
        'plt.tight_layout()\n',
        'plt.show()\n',
    ),
    md(
        "## Section 2 — Signal Engineering\n",
        "\n",
        "Six raw signals per underlying, then causal percentile-rank (5y rolling window) so values are ",
        "comparable across underlyings and regimes. No full-sample lookahead — at each date *t* the ",
        "rank uses only data from *t-5y* to *t*.\n",
        "\n",
        "| Signal | Raw definition | Direction* |\n",
        "|---|---|---|\n",
        "| `rv30` | 30D rolling stdev of log returns × √252 | — |\n",
        "| `vrp` | iv30_atm − rv30 | high → vol-sellers paid more |\n",
        "| `term` | iv90_atm − iv30_atm | high → contango (vol-sellers favoured) |\n",
        "| `skew` | iv30_90mny − iv30_atm | high → expensive tails |\n",
        "| `trend` | log(spot / SMA200) | high → uptrend |\n",
        "| `dd` | spot / rolling-max(252) − 1 | low (negative) → drawdown |\n",
        "\n",
        "*Direction interpretation lives in Section 4 (scorecard); Section 2 just produces the signals.*\n",
    ),
    md("### 2.1 Returns & realized vol\n"),
    code(
        'log_ret = np.log(prices_panel / prices_panel.shift(1))\n',
        'rv30 = log_ret.rolling(window=21, min_periods=15).std() * np.sqrt(252) * 100  # vol pts\n',
        'rv30.tail(3)\n',
    ),
    md("### 2.2 Raw signal panels\n"),
    code(
        'vrp   = iv_panel - rv30\n',
        'term  = iv90_panel - iv_panel\n',
        'skew  = skew_panel.copy()  # already iv30_90mny - iv30_atm from Section 1\n',
        'trend = np.log(prices_panel / prices_panel.rolling(200, min_periods=100).mean())\n',
        'dd    = prices_panel / prices_panel.rolling(252, min_periods=100).max() - 1.0\n',
        '\n',
        'raw_signals = {\n',
        '    "rv30":  rv30,\n',
        '    "vrp":   vrp,\n',
        '    "term":  term,\n',
        '    "skew":  skew,\n',
        '    "trend": trend,\n',
        '    "dd":    dd,\n',
        '}\n',
        'pd.DataFrame({k: v.notna().sum() for k, v in raw_signals.items()}).T.rename(columns=lambda c: c).head()\n',
    ),
    md(
        "### 2.3 Causal percentile rank (5y rolling)\n",
        "\n",
        "Each signal is ranked within its own 5y rolling window, per underlying. Output ∈ [0, 1] where 0.5 ",
        "is the trailing-5y median. Window length is a deliberate balance — long enough to span "
        "GFC/COVID-class episodes (~1y), short enough to adapt to regime change.\n",
    ),
    code(
        'PCT_WINDOW   = 1260  # ~5y of trading days\n',
        'PCT_MIN_OBS  = 252   # 1y warm-up\n',
        '\n',
        'def causal_pct_rank(panel: pd.DataFrame) -> pd.DataFrame:\n',
        '    return panel.rolling(window=PCT_WINDOW, min_periods=PCT_MIN_OBS).rank(pct=True)\n',
        '\n',
        'pct_signals = {k: causal_pct_rank(v) for k, v in raw_signals.items()}\n',
        '\n',
        'pd.DataFrame({k: v.notna().sum() for k, v in pct_signals.items()}).T.rename(\n',
        '    columns=lambda c: c\n',
        ')\n',
    ),
    md(
        "### 2.4 Fragility composite\n",
        "\n",
        "Single \"how stressed is this market\" score blending vol-pricing dimensions. POC weights — ",
        "Phase 4 will rationalize / tune.\n",
        "\n",
        "`fragility = mean(vrp_pct, skew_pct, -trend_pct, -dd_pct)` — high when vol expensive, skew steep, ",
        "trend weak, drawdown deep. Range ∈ [0, 1] (each component is a percentile rank, "
        "negation flips so all components point the same way).\n",
    ),
    code(
        'def _flip(p): return 1.0 - p\n',
        '\n',
        'fragility = (\n',
        '    pct_signals["vrp"]\n',
        '    + pct_signals["skew"]\n',
        '    + _flip(pct_signals["trend"])\n',
        '    + _flip(pct_signals["dd"])\n',
        ') / 4.0\n',
        '\n',
        'pct_signals["fragility"] = fragility\n',
        'fragility.tail(3)\n',
    ),
    md("### 2.5 Latest signal snapshot\n"),
    code(
        'latest = pd.DataFrame({\n',
        '    sig: panel.iloc[-1] for sig, panel in pct_signals.items()\n',
        '}).T\n',
        'latest.style.background_gradient(cmap="RdYlGn_r", vmin=0, vmax=1).format("{:.2f}") if hasattr(latest, "style") else latest\n',
    ),
    md("### 2.6 Signal time-series\n"),
    code(
        'sigs_to_plot = ["vrp", "skew", "term", "trend", "dd", "fragility"]\n',
        'fig, axes = plt.subplots(len(sigs_to_plot), 1, figsize=(12, 2*len(sigs_to_plot)), sharex=True)\n',
        'for ax, sig in zip(axes, sigs_to_plot):\n',
        '    pct_signals[sig].plot(ax=ax, lw=0.9)\n',
        '    ax.axhline(0.5, color="grey", ls="--", lw=0.5)\n',
        '    ax.set_ylim(0, 1)\n',
        '    ax.set_title(f"{sig} (causal 5y pct rank)", fontsize=10)\n',
        '    ax.legend(loc="upper left", fontsize=8)\n',
        'plt.tight_layout()\n',
        'plt.show()\n',
    ),
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB.write_text(json.dumps(nb, indent=1), encoding="utf-8")
print(f"wrote {NB} ({len(cells)} cells)")
